/// <reference types="nativewind/types" />

// What teaches `View`, `Text`, `Pressable` and the rest that `className` is a prop. Without it
// every component in `registry/ui` fails to typecheck on its own styling. Generated by NativeWind;
// committed rather than gitignored, because a consumer cloning this repo needs it to typecheck too.
