/**
 * Emits the three encodings of `tokens/palette.mjs`.
 *
 * Run with `--check` to verify the committed output is current without writing
 * (what CI does), mirroring cubeui's `git diff --exit-code -- public/r` guard.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { dark, light, names, radius } from "../tokens/palette.mjs";
import { formatOklch, isOutOfGamut, toNativeCss } from "./oklch.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
const check = process.argv.includes("--check");

/** `--color-x: var(--x)` for every token: the Tailwind 4 `@theme inline` bridge. */
const themeInline = () =>
  [
    "@theme inline {",
    "  --radius-sm: calc(var(--radius) - 4px);",
    "  --radius-md: calc(var(--radius) - 2px);",
    "  --radius-lg: var(--radius);",
    "  --radius-xl: calc(var(--radius) + 4px);",
    ...names.map((n) => `  --color-${n}: var(--${n});`),
    "}",
  ].join("\n");

const block = (selector, map, format, withRadius) =>
  [
    `${selector} {`,
    ...(withRadius ? [`  --radius: ${radius};`] : []),
    ...names.map((n) => `  --${n}: ${format(map[n])};`),
    "}",
  ].join("\n");

const WEB = `/* Generated by scripts/build-tokens.mjs from tokens/palette.mjs. Do not edit. */

${block(":root", light, formatOklch, true)}

${block(".dark", dark, formatOklch, false)}

${themeInline()}
`;

const NATIVE = `/* Generated by scripts/build-tokens.mjs from tokens/palette.mjs. Do not edit. */

/*
 * Hex and rgba, not oklch: React Native's style engine cannot parse a modern
 * colour space at runtime. Same token names and same order as the web build —
 * only the encoding differs.
 *
 * Not \`@import "tailwindcss"\`, which would put every utility in \`@layer utilities\`.
 * react-native-web gives each component a base class in a plain, unlayered
 * stylesheet, and an unlayered rule beats a layered one whatever the layer order
 * or specificity. Layered utilities therefore lose every property that base class
 * sets: \`p-4\` renders with no padding and \`flex-row\` stays a column, while
 * \`gap-4\` and \`rounded-xl\` work — which is what makes the failure so confusing.
 * Importing the utilities unlayered puts them in the same cascade, where they win
 * on document order.
 */
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";

${block(":root", light, toNativeCss, true)}

${block(".dark", dark, toNativeCss, false)}

${themeInline()}
`;

const camel = (n) => n.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const themeTs = () => {
  const set = (map) => names.map((n) => `  ${camel(n)}: "${toNativeCss(map[n])}",`).join("\n");
  return `/* Generated by scripts/build-tokens.mjs from tokens/palette.mjs. Do not edit. */

/**
 * The palette again, in TypeScript.
 *
 * React Native props that take a colour — \`placeholderTextColor\`, icon tints,
 * the navigator's chrome, SVG fills — are plain strings and cannot read a CSS
 * variable, so those values have to exist here as well as in the stylesheet.
 * Both come from the same source, so they cannot drift.
 */
export const light = {
${set(light)}
} as const;

export const dark = {
${set(dark)}
} as const;

export type ColorName = keyof typeof light;
export type Palette = Record<ColorName, string>;

/** Pick a palette from RN's \`useColorScheme()\`, which returns null before it resolves. */
export const paletteFor = (scheme /*: "light" | "dark" | null | undefined */) =>
  scheme === "dark" ? dark : light;
`;
};

const outputs = [
  ["tokens.web.css", WEB],
  ["tokens.native.css", NATIVE],
  ["theme.ts", themeTs()],
];

let stale = 0;
if (!check) mkdirSync(dist, { recursive: true });
for (const [name, body] of outputs) {
  const path = join(dist, name);
  if (check) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (current !== body) {
      stale++;
      console.error(`  stale   dist/${name}`);
    } else console.log(`  ok      dist/${name}`);
  } else {
    writeFileSync(path, body);
    console.log(`  wrote   dist/${name}`);
  }
}

// A clamped colour is silently wrong on device, so say so — but shadcn's own
// destructive is out of sRGB, so this is a note and not a failure.
const clipped = names.flatMap((n) =>
  [
    ["light", light[n]],
    ["dark", dark[n]],
  ]
    .filter(([, t]) => isOutOfGamut(t))
    .map(([mode]) => `${n} (${mode})`),
);
if (clipped.length) console.log(`\n  note: clamped to sRGB — ${clipped.join(", ")}`);

if (check && stale) {
  console.error(`\n${stale} file(s) out of date. Run: npm run tokens:build`);
  process.exit(1);
}
