/**
 * Emits the three encodings of `tokens/palette.mjs`.
 *
 * Run with `--check` to verify the committed output is current without writing
 * (what CI does), mirroring cubeui's `git diff --exit-code -- public/r` guard.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { dark, light, names, radius } from "../tokens/palette.mjs";
import { formatOklch, isOutOfGamut, toNativeCss } from "./oklch.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
const check = process.argv.includes("--check");

/** `--color-x: var(--x)` for every token: the Tailwind 4 `@theme inline` bridge. */
const themeInline = () =>
  [
    "@theme inline {",
    "  --radius-sm: calc(var(--radius) - 4px);",
    "  --radius-md: calc(var(--radius) - 2px);",
    "  --radius-lg: var(--radius);",
    "  --radius-xl: calc(var(--radius) + 4px);",
    ...names.map((n) => `  --color-${n}: var(--${n});`),
    "}",
  ].join("\n");

const block = (selector, map, format, withRadius, indent = "") =>
  [
    `${indent}${selector} {`,
    ...(withRadius ? [`${indent}  --radius: ${radius};`] : []),
    ...names.map((n) => `${indent}  --${n}: ${format(map[n])};`),
    `${indent}}`,
  ].join("\n");

const WEB = `/* Generated by scripts/build-tokens.mjs from tokens/palette.mjs. Do not edit. */

/*
 * The two stylesheets a compiled component needs and cannot ask for itself.
 *
 * A registry item ships \`.tsx\` files, and a \`.tsx\` file cannot declare that its classes come
 * from somewhere. So a DOM consumer who installs \`@cubeui/toggle-chip\` gets markup wearing
 * \`cube-rn-view\` and \`animate-in\` with nothing in their tree defining either, and the component
 * renders — unstyled, in the wrong direction, with no error anywhere to say why. This file is the
 * one thing every consumer installs, so it is where the two get said.
 *
 * \`cubeui-reset.css\` is the compiler's own, installed beside this file. React Native source
 * legitimately omits classes the DOM then needs, because Yoga supplies the defaults and CSS does
 * not: no RN author writes \`flex-col\`, because a \`<View>\` already stacks that way. On web
 * react-native-web closes that gap with a per-component base class, and a compiled component has
 * no react-native-web — this replaces it. 24 of the compiled components wear one of its classes.
 *
 * \`tw-animate-css\` is where \`animate-in\`, \`fade-in-0\`, \`zoom-in-95\` and \`slide-in-from-*\` live.
 * They are not core Tailwind utilities and never were: shadcn's own \`init\` writes this same import
 * into an app's stylesheet, which is why a component copied out of shadcn's registry appears to
 * work without declaring it. Five items here use them — \`dialog\`, \`popover\`, \`menu\`, \`select\` and
 * \`tooltip\` — and what is lost without it is not the animation but the \`data-[state]\` rules
 * around it.
 *
 * Both are \`@import\` and not a \`dependencies\` entry per item, because the question is not which
 * component needs them — it is whether the stylesheet the app already loads defines the classes
 * its components name. \`tw-animate-css\` is still declared as a package, since a bare specifier
 * has to resolve to something installed.
 */
@import "tw-animate-css";
@import "./cubeui-reset.css";

${block(":root", light, formatOklch, true)}

${block(".dark", dark, formatOklch, false)}

${themeInline()}
`;

const NATIVE = `/* Generated by scripts/build-tokens.mjs from tokens/palette.mjs. Do not edit. */

/*
 * Hex and rgba, not oklch: React Native's style engine cannot parse a modern
 * colour space at runtime. Same token names and same order as the web build —
 * only the encoding differs.
 *
 * Not \`@import "tailwindcss"\`, which would put every utility in \`@layer utilities\`.
 * react-native-web gives each component a base class in a plain, unlayered
 * stylesheet, and an unlayered rule beats a layered one whatever the layer order
 * or specificity. Layered utilities therefore lose every property that base class
 * sets: \`p-4\` renders with no padding and \`flex-row\` stays a column, while
 * \`gap-4\` and \`rounded-xl\` work — which is what makes the failure so confusing.
 * Importing the utilities unlayered puts them in the same cascade, where they win
 * on document order.
 */
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";

/*
 * The lines of Tailwind's preflight a web build needs, without the rest of it, which would
 * fight react-native-web's own reset. Preflight is the only thing that sets \`border-box\` on \`*\`.
 * react-native-web sets it on every element it renders, so a \`View\` or a \`Pressable\` never
 * noticed; a \`.web.tsx\` half that renders a raw \`<input>\` or \`<textarea>\` fell back to the
 * browser's \`content-box\`, and an \`h-10 py-2\` input drew 58px tall beside a 40px button.
 *
 * Here and not as \`box-border\` on each raw-DOM class, so the next raw-DOM half is covered before
 * anyone knows it needs to be. Unlayered and specificity zero, so any utility still overrides it.
 * Native never sees it: Yoga is always border-box, and react-native-css drops a universal selector
 * without a word — \`tokens-dark.test.mjs\` asserts that it contributes nothing on device.
 */
*,
::before,
::after {
  box-sizing: border-box;
}

/*
 * More lines of preflight, for the same raw-DOM halves and for the same reason. A \`.web.tsx\`
 * half that renders a radix part renders a raw \`<button>\` — a tab trigger, a dialog's close — and
 * the user-agent sheet gives it a \`2px outset\` border, a grey fill, and a colour and font of its
 * own rather than inherited ones: an inactive tab ignored its list's \`text-muted-foreground\` and
 * drew outset. Nothing sets a page font either, so a raw \`<label>\` drew in the browser's serif.
 * The font is react-native-web's own stack, which every \`Text\` already wears.
 *
 * Unlayered and specificity zero, like the line above, so any utility still overrides it. That
 * holds because this file imports the utilities unlayered too: all of them share one cascade, and
 * a utility is a class, (0,1,0) at the least, so it wins on specificity before document order is
 * consulted. (An unlayered rule beats every layered one, so this would *not* be safe beside an
 * \`@layer utilities\` — which is the other reason this file never imports them that way.)
 * \`:where()\` rather than a bare \`button\`, so it outranks nothing — not even an app's own
 * unlayered \`button { }\` rule.
 * react-native-web's base class is a class as well, so a \`Pressable\`, which it renders as a
 * \`<button>\`, keeps its own look. Native never sees these: react-native-css drops an element
 * selector as silently as it drops \`*\` — \`tokens-dark.test.mjs\` asserts that too.
 *
 * The form fields are the rest of preflight's control reset (#103). \`input.web.tsx\` and
 * \`textarea.web.tsx\` render a raw \`<input>\` and \`<textarea>\`, which do not inherit the page
 * font: the user-agent sheet drew the input in Arial and the textarea in monospace. Only \`color\`
 * and \`font\` — their border and fill are the component's classes, not a browser look to undo.
 * \`color: inherit\` reaches the element and not its \`::placeholder\`, so a
 * \`placeholder:text-muted-foreground\` still colours the hint, and a \`text-*\` class still wins.
 */
:where(button) {
  border: 0 solid;
  background-color: transparent;
  color: inherit;
  font: inherit;
}

:where(input, select, textarea) {
  color: inherit;
  font: inherit;
}

:where(html) {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
}

${block(":root", light, toNativeCss, true)}

/*
 * A media query and not \`.dark\`, which is what the web build emits and what every
 * shadcn stylesheet has — because on native it silently does nothing.
 *
 * There is no DOM and no root element to carry a class, so react-native-css only
 * recognises a dark *variable* block written as \`@media (prefers-color-scheme: dark)\`.
 * A bare \`.dark { }\` compiles without complaint into an ordinary class style named
 * \`dark\`: variables scoped to whatever subtree you hand \`className="dark"\`, rather
 * than the root set. Running the committed file through the compiler says it plainly
 * — 18 root variables, 0 of them carrying a dark value — and every app installing it
 * would render light for ever with nothing in the build to say so. That is what
 * \`tokens-dark.test.mjs\` now holds.
 *
 * \`.dark:root\` looks like the fix and is not: the compiler rejects it outright with
 * "Class-qualified :root selectors are unsupported on native", even though its own
 * \`selectors.ts\` still carries a matcher for that spelling.
 *
 * The consequence for consumers is that native follows the **system** appearance.
 * An in-app theme toggle is \`Appearance.setColorScheme("dark")\` from react-native,
 * not a class on a wrapper — a different mechanism from web's \`.dark\` on \`<html>\`,
 * and the one place the two platforms' theming does not look alike. The two blocks
 * after this one are how the same file gives an Expo *web* build the class as well.
 */
@media (prefers-color-scheme: dark) {
${block(":root", dark, toNativeCss, false, "  ")}
}

/*
 * The manual override, for web only: \`class="dark"\` or \`class="light"\` on \`<html>\` beats the
 * system in either direction, which is what a light / dark / system picker needs. On device that
 * picker calls \`Appearance.setColorScheme\`, which moves the media query above; on web nothing inside
 * the app can move \`prefers-color-scheme\`, so without these a picker could only follow the system.
 *
 * Spelled \`:is(html.dark)\` because that is the spelling that works on both platforms. It is
 * (0,1,1), so it outranks the media query's \`:root\` (0,1,0) whatever the system says, and
 * react-native-css drops it on native without a word. Each obvious alternative breaks the device
 * build instead:
 *
 * - \`:root.dark\` — and \`html:root.dark\`, and either inside \`@media\` or \`@supports\` — fails the
 *   compile outright: "Class-qualified :root selectors are unsupported on native".
 * - \`.dark\`, \`html.dark\` and \`html:is(.dark)\` compile into a class style named \`dark\`, which is
 *   the scoped-variables bug the note above describes, back again.
 * - \`:where(.dark)\` is dropped as well, but it is specificity zero and loses to the media query.
 *
 * \`tokens-dark.test.mjs\` holds it: the compiled native output is identical with or without them.
 */
${block(":is(html.dark)", dark, toNativeCss, false)}

${block(":is(html.light)", light, toNativeCss, false)}

${themeInline()}
`;

const camel = (n) => n.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const themeTs = () => {
  const set = (map) => names.map((n) => `  ${camel(n)}: "${toNativeCss(map[n])}",`).join("\n");
  return `/* Generated by scripts/build-tokens.mjs from tokens/palette.mjs. Do not edit. */

/**
 * The palette again, in TypeScript.
 *
 * React Native props that take a colour — \`placeholderTextColor\`, icon tints,
 * the navigator's chrome, SVG fills — are plain strings and cannot read a CSS
 * variable, so those values have to exist here as well as in the stylesheet.
 * Both come from the same source, so they cannot drift.
 */
export const light = {
${set(light)}
} as const;

export const dark = {
${set(dark)}
} as const;

export type ColorName = keyof typeof light;
export type Palette = Record<ColorName, string>;

/**
 * Pick a palette from RN's \`useColorScheme()\`, which returns null before it resolves.
 *
 * Which scheme that hook reports follows the **system** appearance, because the
 * stylesheet beside this file keys its dark palette off
 * \`@media (prefers-color-scheme: dark)\` — the only form react-native-css honours on
 * device. An in-app theme toggle is therefore
 * \`Appearance.setColorScheme("dark")\` from react-native, which moves both this and
 * the stylesheet together. It is *not* a \`.dark\` class on a wrapper: that is the web
 * mechanism, and on native it silently styles nothing.
 */
export const paletteFor = (scheme: "light" | "dark" | null | undefined): Palette =>
  scheme === "dark" ? dark : light;
`;
};

const outputs = [
  ["tokens.web.css", WEB],
  ["tokens.native.css", NATIVE],
  // Namespaced because the `tokens` item installs it as a `registry:lib`, which lands in the
  // consumer's `lib/` under this basename, and `theme.ts` is a name apps already use: it overwrote
  // telos's own theme-preference module on `shadcn add`, without a prompt.
  ["cubeui-theme.ts", themeTs()],
];

let stale = 0;
if (!check) mkdirSync(dist, { recursive: true });
for (const [name, body] of outputs) {
  const path = join(dist, name);
  if (check) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (current !== body) {
      stale++;
      console.error(`  stale   dist/${name}`);
    } else console.log(`  ok      dist/${name}`);
  } else {
    writeFileSync(path, body);
    console.log(`  wrote   dist/${name}`);
  }
}

// A clamped colour is silently wrong on device, so say so — but shadcn's own
// destructive is out of sRGB, so this is a note and not a failure.
const clipped = names.flatMap((n) =>
  [
    ["light", light[n]],
    ["dark", dark[n]],
  ]
    .filter(([, t]) => isOutOfGamut(t))
    .map(([mode]) => `${n} (${mode})`),
);
if (clipped.length) console.log(`\n  note: clamped to sRGB — ${clipped.join(", ")}`);

if (check && stale) {
  console.error(`\n${stale} file(s) out of date. Run: npm run tokens:build`);
  process.exit(1);
}
